sudo: false
language: node_js
install:
  - npm install
  - npm install -g codecov
cache:
  directories:
    - node_modules
node_js:
  - node
branches:
  only:
    - master
script:
  - npm run build
after_success:
  - codecov